// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkIcon: typeof import('./src/components/DarkIcon.vue')['default']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCard: typeof import('@layui/layui-vue')['LayCard']
    LayCol: typeof import('@layui/layui-vue')['LayCol']
    LayColorPicker: typeof import('@layui/layui-vue')['LayColorPicker']
    LayConfigProvider: typeof import('@layui/layui-vue')['LayConfigProvider']
    LayContainer: typeof import('@layui/layui-vue')['LayContainer']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayException: typeof import('@layui/layui-vue')['LayException']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayIcon: typeof import('@layui/icons-vue')['LayIcon']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayLogo: typeof import('@layui/layui-vue')['LayLogo']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayResult: typeof import('@layui/layui-vue')['LayResult']
    LayRow: typeof import('@layui/layui-vue')['LayRow']
    LayScroll: typeof import('@layui/layui-vue')['LayScroll']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTab: typeof import('@layui/layui-vue')['LayTab']
    LayTabItem: typeof import('@layui/layui-vue')['LayTabItem']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LightIcon: typeof import('./src/components/LightIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
